### PR TITLE
Global flag to enable flushing write buffer after

### LINKED ISSUE #128: Segmenter does not deliver segments consistently
The current segmenter works by:

* Polling for the existence of the *next* segment as a signal the current one is complete
* Reading the corresponding playlist to extract the duration, polling if the playlist is not ready.
* Returning the segment bytes and duration to the app.

The minimum poll interval for both the segment and playlist monitors are 100ms, and they are run sequentially.

This approach has a number of issues.

* There is significant variability in when a segment is made available to the goclient. This is primarily due to the polling strategy; observe that repeated runs of 1-1 B/O will show drops in mostly identical places. Filesystem latency contributes a little bit; running the datadir out of tmpfs increases the success rate ~4%. For data from one run, see https://gist.github.com/j0sh/69d1efc93b06ede46d97de939294c0e8

* Segmenter acts on a finite window and removes older segments from disk beyond the window. This will lead to issues with VOD or videos coming in faster than realtime. The original intent was to prune files to minimize disk usage, but we will likely want to revisit persistence at some point for various reasons.

* Seems to have issues processing small segment sizes. https://github.com/livepeer/go-livepeer/issues/885

There are a couple possible solutions.

* Check whether filesystem monitoring (eg, inotify via fsnotify) would improve consistency of segment delivery.

* Implement a segmenter in-process within the goclient. This should also mitigate the need to drop the first few seconds of the stream to synchronize on a keyframe.

### LINKED ISSUE #885: Segmenter buffers small segments
**Describe the bug**
If segments are small (in bytes), segmener buffers them internally and then spits outs them all at once, up to three segments together. 

**To Reproduce**
1. Generate test video
`ffmpeg -f lavfi -i sine=frequency=1000:duration=60 -c:a aac -f lavfi -i testsrc=duration=60:size=1280x720:rate=30 -g 60 output2-60-2.mp4`

2. Start broadcaster with one orchestrator.
3. Stream test video into broadcaster.
4. Observe segment two and three emerged at the same and not being transcoded.

**Expected behavior**
All segments should be transcoded with only one orchestrator, no matter the segment size.

**Additional context**
This is not a problem by itself, but it surfaces problems with orchestrator selection and distribution of work inside orchestrator.

### PR DESCRIPTION
**Pull request by darkdarkdragon**
Global flag to enable flushing write buffer after
each `writeAVTag` call.
Fixes issue with small segments not arriving at time when
re-streaming RTMP stream.
Fixes livepeer/lpms#128
Fixes livepeer/go-livepeer#885

### CODE REVIEW

**Review by mk-livepeer — COMMENTED** [review]
If a global flag is really what we want, then the code change here looks fine.

However, it might be more idiomatic to add a `FlushEachAVTag bool` member to `type Conn struct`, and pass this in optionally each time a new `Conn` is created.

I just traced the code though, and it looks like doing the above would be very annoying.  It would incur a change to the signature of several public exported functions, and might be more trouble than it's worth.  (I'm just sharing my thoughts)

It makes me wonder - is this something that we would always have enabled?  Is there ever a reason to disable it?

I wonder if it makes sense to leave this as an option, or to just make this the new behavior.

**Comment by j0sh** [comment]
I'd make flushing the default behavior - that is, remove the flag and flush unconditionally.

**Comment by darkdarkdragon** [comment]
Removed flag.

**Comment by mk-livepeer** [comment]
@darkdarkdragon did you change your mind?  why did you close it?

**Comment by darkdarkdragon** [comment]
@mk-livepeer it was mistake. Was deleting another branch with same changes I was used for testing.

**Review by mk-livepeer — APPROVED** [review]
👍 LGTM

**Pull request merged**
