### PR TITLE
merge `livepeer` branch to `livepeer/master`

### PR DESCRIPTION
**Pull request by mk-livepeer**
go dependency management is tricky enough as it is - it will make life easier for us all if we merge the `livepeer/livepeer` branch to `livepeer/master`

With this merged, the command:
```
go get github.com/livepeer/lpms
```
will fetch lpms along with the *correct* dependency version of `joy4`

Otherwise, users of standalone `lpms` have to check out the `livepeer` branch of `joy4` explicitly.

### CODE REVIEW

**Comment by j0sh** [comment]
How does this make it easier?

**Comment by mk-livepeer** [comment]
@j0sh , When a user does:
```go get github.com/livepeer/lpms```
Under the current state, they will get the wrong version of `joy4`

After merging this PR, the command:
```go get github.com/livepeer/lpms``` will fetch lpms along with the *correct* dependency version of `joy4`

**Comment by darkdarkdragon** [comment]
@mk-livepeer @j0sh 
I agree with Micheal here - looks like merging our change into `master` is our only option for not breaking dependencies - at least till `go mod` will be made mandatory.

Probably we still should add our changes into `livepeer` branch - just to keep track - and merge them into `master`

**Review by darkdarkdragon — APPROVED** [review]
LGTM

**Comment by j0sh** [comment]
What's stopping us from making `go mod` mandatory for LPMS right now? Using vanilla `go get` is going to break any time we need to pin something specific commit or branch, so this doesn't seem like an especially unique situation.

**Comment by darkdarkdragon** [comment]
I don't know how to prevent it from being build using old way (without `go mod`),
but I agree with your point about pinning specific branches.
So let's use `livepeer` branch here and move our own build process of `lpms` and `go-livepeer` to `go mod`.

**Comment by j0sh** [comment]
> I don't know how to prevent it from being build using old way

Don't know if it's worth trying to prevent. But we should definitely be loud and specific that `go mod` is basically required if someone wishes to use LPMS standalone.

**Comment by mk-livepeer** [comment]
verbally approved by @j0sh during today's call

**Pull request merged**
